version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12

    pre_build:
        commands:
            - npm ci

    build:
        commands:
            - npm ci
            - npm run fullBuild publisher=awscibuild
            - VCS_COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
            - CI_BUILD_URL=$(echo $CODEBUILD_BUILD_URL | sed 's/#/%23/g') # Encode `#` in the URL because otherwise the url is clipped in the Codecov.io site
            - CI_BUILD_ID="${CODEBUILD_BUILD_ID}"
            - test -n "$CODE_COV_TOKEN" && curl -s https://codecov.io/bash > codecov.sh || true # this sometimes times out but we don't want to fail the build
            - test -n "$CODE_COV_TOKEN" && bash ./codecov.sh -t $CODE_COV_TOKEN || true

reports:
    unit-test:
        files:
            - '*'
        base-directory: '.test-reports'
        file-format: JunitXml
