version: 0.2
phases:
    install:
        commands:
            - |
                if(-Not($Env:CODE_COV_TOKEN -eq $null)) {
                    choco install -y --no-progress codecov
                }
                choco install -y --no-progress nodejs-lts --version 16.20.2
    pre_build:
        commands:
            - node --version
            - npm --version
    build:
        commands:
            - npm ci
            - npm run fullBuild publisher=awscibuild
            - $env:TEST_REPORT_DIR="$env:CODEBUILD_SRC_DIR/.test_reports"; npm run test
            - |
                if(-Not($Env:CODEBUILD_BUILD_SUCCEEDING -eq "0" -Or $Env:CODE_COV_TOKEN -eq $null)) {
                  $env:VCS_COMMIT_ID=$Env:CODEBUILD_RESOLVED_SOURCE_VERSION;
                  $env:CI_BUILD_URL=[uri]::EscapeUriString($Env:CODEBUILD_BUILD_URL);
                  $env:CI_BUILD_ID=$Env:CODEBUILD_BUILD_ID;
                  codecov -t $Env:CODE_COV_TOKEN `
                    --flag unittest `
                    -f "build/reports/jacoco/coverageReport/coverageReport.xml" `
                    -c $Env:CODEBUILD_RESOLVED_SOURCE_VERSION
                }
reports:
    unit-test:
        files:
            - 'testReport.xml'
        base-directory: '$env:CODEBUILD_SRC_DIR/.test-reports'
        file-format: JUNITXML
