name: Node.js CI for AWS ADO toolkit

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup
              run: |
                  npm install npm@latest -g
                  npm install
                  npm run fullBuild
            - name: Check
              run: |
                  node package/Tasks/AWSCLI/AWSCLI.js
